language: cpp
python:
  - "3.4"

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8.3

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
  - sudo pip3 install --upgrade --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - chmod +x ci/download.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install openssl;
      mkdir -p /usr/local/lib;
      ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
      ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install v6.0.0;
    fi
install:
  - pushd ci
  - ./download.sh
  - popd

script:
  - ulimit -n 4096
  - powershell -File ci/init.ps1