language: cpp

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8.1

matrix:
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install openssl;
      mkdir -p /usr/local/lib;
      ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
      ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
      rvm install ruby-2.3.1;
      rvm use 2.3.1;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install v6.0.0;
    fi

install:
  - pushd Travis
  - ./download.sh
  - popd

script:
  - ulimit -n 4096
  - powershell -File Travis/travis.ps1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mdspell '**/*.md' '!powershell/**/*.md' --ignore-numbers --ignore-acronyms --report;
    fi