language: cpp
python:
- '3.4'
git:
  depth: 1000
os:
- linux
- osx
sudo: required
dist: trusty
osx_image: xcode8.3
notifications:
  slack:
    rooms:
      secure: JQZ3Jnam8qQoKFGeiqBZ9vtYeEZyt81WM5LXHtVaiDTDldc9K7KQR3j0j9ubAS01TM4go6PYJ8yW3AoxTlUISejJgJQJahgrLhfwqNv77TpvCuJH9iuwarS8b3KCo72owxyw+rLWz4UX0x+e+RVuuDRA2HhvOGxOP56FcW/Ix75ZGOVCWRTbgkagKLfbOwUuuWFH6MNfqdD4lVtQ97nxzypNUJ+iakKQmpxFKo01d79azTpfmvcr+uttkIZawu0vXdiZp8UUXqiMNGPg7yykMUm9bF1EkJ1b5/RAbsl8nvhWHrsFUv659CWsxp9LlGdJ9iXueV7SCdHsd6ZzDTwVXpJo/YTtVMjyhZKuUBKk/v/kPNUbelTIr5KlnqTF/Tb2dS38ADGDHS52ZDwBtCkPTrkZmgnckxF5g6uv8v15GWbatnntLIdyGoNQgAqPDYatuK/Jf13LmqOZg3kh6W8/L86+WEqHFuybpk7i27NW8YKYgzjDMa6Hyo5BLZK/33UCImf8qfEtp2K13a7WLeUsCmIuThIwhY8MtBIT3c24WdDnFXdHveDzFvKaPTjsMdyNUnpfGXmyMDnWDsKMjuR2FHjZeMcTAPFuDa4d2Peq7Yn4vqplaagyA59h+EeK1D4bHT+JuuJ+FwhEPUooU+vllP+/Z99O2wALXfD2m3fTuhE=
    on_success: always
    on_failure: always
    on_start: always
  webhooks:
    urls:
      secure: coj3rE5uWYR+fEnlkQ5jN5PMQuBY0JjuG5IENWCFachTM+TUCvVeYa7/jN0EVbWvbOTrqSsK0SzaD8Ycgf7ZloLdt4nU5gDVP60EDfASPiB3x7/VQgqjGJlH85Cu5CIa983MRrOVEcMwJVAiDkZ1Ima5Hwtmjnk1iXPBSp1x3dKwCaGOFpwWRvvAHPpwOrBJtZauXQ3YdvaIguLfzFvjcFUyb2P7vThE14U7owEeBTkSLd6w1BGhYkOuXUhO+DyxgWRgrcbJ+69D2q164Kzq9cBX9AoYWvvxiTwiEUssGeb2mZ8lCA9x74d5uZMsfFdW6Ik/FypLJKulIeyfwvdlblEsEY57Xzm29c6g7C5pgb1IkUPFajOQ1djzjEqaQRG4NW/xO+P4RABM/EE/z8PqkUPxvkUVyBs2HVE2E/NSh3wD1MlX5jqMMNf1Hol/oRtnAlHUmMiNF6WiNn7sYGbfZhYiHCP6P/yx58MZRp4Gm75vZJOkJ4d9Qlop56BsNtwt6c6P3rwgNQlzeptODYDSnflfPMKMySDy3re550ClvEUbEEkFw6QeJFeWBorw2wqz55gLN8sCdj1j71SCh4fNYpVJgMKZpeS19QLcx3PkS/pbBN9ZmmUJEen1ANxUgp8ENb7btBsAYmEs3zBr6bcFqzbFU6iEQynA/7ZRU0zsvqQ=
    on_success: always
    on_failure: always
    on_start: always
before_install:
- chmod +x ci/download.sh
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; brew
  install python3; mkdir -p /usr/local/lib; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install python3; nvm
  install v6.0.0; fi
install:
- pushd ci
- "./download.sh"
- popd
before_script:
- export PATH=~/.local/bin:$PATH
script:
- ulimit -n 4096
- pwsh -File ci/init.ps1
