# Welcome to Jekyll!
#

# Site settings
title: Vaporshell
description: |
  Define your Cloud   
  with Powershell   
  on any system   
owner: "SCRT HQ"
first_published: 2017
email: nate@scrthq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vaporshell.io" # the base hostname & protocol for your site
permalink: /:category/:title
highlighter: rouge
google_analytics: UA-101420411-1
gems:
  - jemoji
social:
  github: https://github.com/scrthq/Vaporshell
  linkedin-square: https://linkedin.com/in/scrthq
  #reddit: https://www.reddit.com/user/scrthq/
  #stack-overflow: https://stackoverflow.com/users/5302680/nferrell
  #soundcloud: https://soundcloud.com/nonfuture
  gratipay: https://gratipay.com/Vaporshell/
  paypal: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GU6CJMFGVP6ZS
  email: mailto:nate@vaporshell.io
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #vimeo:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
