# Welcome to Jekyll!
#

# Site settings
title: Vaporshell
description: |
  Define your Cloud   
  with Powershell   
  on any system   
owner: SCRT HQ # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: nate@scrthq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vaporshell.io" # the base hostname & protocol for your site
social:
  linkedin-square: https://linkedin.com/in/scrthq
  github: https://github.com/nferrell
  email: mailto:nate@vaporshell.io
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
