# See http://www.appveyor.com/docs/appveyor-yml for many more options

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1

# Send Slack notifications for build updates
notifications:
- provider: Slack
  incoming_webhook:
    secure: Cne/08qwOJL4+nAQHifbb8TGBv3/0YgOg8eZkQej8W1WLwlE1Y0qNTdxbtXZVV2q55Q4pOjmCIXcbbjnEcxKGf1EQRwdcFoIWqbRGcPM8sQ=r4jhjYzU3uyKHTbfZRAr