image: 
  - Ubuntu
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt
  Coveralls:
    secure: r4c1f5ysoobhV4DGF9zc18yl+buyh7LoV7kRr7aUFvrcjd7VFmj71EPN0Egs9gOQ
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

matrix:
  fast_finish: true

skip_commits:
  message: /updated readme.*|update readme.*s|\[skip ci\]|\[ci skip\]/

only_commits:
  message: /!deploy|!build|!ci|\[ci\]/

build: false

init:
  - ps: Write-Host $env:PYTHON $env:PYTHON_VERSION $env:PYTHON_ARCH

install:
  - sh: | 
      sudo apt-get -y install python-pip python-dev build-essential
      sudo pip install --upgrade pip
      sudo pip install --upgrade virtualenv
      sudo pip install cfn_flip
  - cmd: "%PYTHON%/Scripts/pip.exe install cfn_flip"

test_script:
  - pwsh: | 
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -notlike '*2015*') {
        $string = "Running PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'"
        Add-AppveyorMessage -Message $string -Category Information
        Write-Host -ForegroundColor Magenta $string
        . .\ci\init.ps1
      } else { 
        $string = "Skipping PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'"
        Add-AppveyorMessage -Message $string -Category Warning
        Write-Warning $string
      }
  - ps: |
      $string = "Running PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'"
      Add-AppveyorMessage -Message $string -Category Information
      Write-Host -ForegroundColor Magenta $string
      . .\ci\init.ps1image: 
  - Ubuntu
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt
  Coveralls:
    secure: r4c1f5ysoobhV4DGF9zc18yl+buyh7LoV7kRr7aUFvrcjd7VFmj71EPN0Egs9gOQ
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

matrix:
  fast_finish: true

skip_commits:
  message: /updated readme.*|update readme.*s|\[skip ci\]|\[ci skip\]/

only_commits:
  message: /!deploy|!build|!ci|\[ci\]/

build: false

init:
  - ps: Write-Host $env:PYTHON $env:PYTHON_VERSION $env:PYTHON_ARCH

install:
  - sh: |-
      sudo apt-get -y install python-pip python-dev build-essential
      sudo pip install --upgrade pip
      sudo pip install --upgrade virtualenv
      sudo pip install cfn_flip
  - cmd: "%PYTHON%/Scripts/pip.exe install cfn_flip"

test_script:
  - pwsh: |-
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -notlike '*2015*') {
      $string = "Running PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'";
      Add-AppveyorMessage -Message $string -Category Information;
      Write-Host -ForegroundColor Magenta $string;
      . .\ci\init.ps1; } else { 
      $string = "Skipping PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'";
      Add-AppveyorMessage -Message $string -Category Warning;
      Write-Warning $string; }
  - ps: |-
      $string = "Running PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'";
      Add-AppveyorMessage -Message $string -Category Information;
      Write-Host -ForegroundColor Magenta $string;
      . .\ci\init.ps1;