environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt
  Coveralls:
    secure: r4c1f5ysoobhV4DGF9zc18yl+buyh7LoV7kRr7aUFvrcjd7VFmj71EPN0Egs9gOQ
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PSVersion: Core
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PSVersion: Core
      PYTHON: "C:\\Python27"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PSVersion: Windows
      PYTHON: "C:\\Python27"

matrix:
  fast_finish: true

skip_commits:
  message: /updated readme.*|update readme.*s|\[skip ci\]|\[ci skip\]/

only_commits:
  message: /!deploy|!build|!ci|\[ci\]/

build: false

install:
  - sh: |
      sudo -H apt-get -y install python-pip python-dev build-essential
      sudo -H pip install --upgrade pip
      sudo -H pip install --upgrade virtualenv
      sudo -H pip install --upgrade setuptools
      sudo -H pip install cfn_flip
  - cmd: "%PYTHON%/Scripts/pip.exe install cfn_flip"
test_script:
  - pwsh: if ($env:PSVersion -eq 'Core') {. .\build.ps1}
  - ps: if ($env:PSVersion -eq 'Windows') {. .\build.ps1}
