# See http://www.appveyor.com/docs/appveyor-yml for many more options

# set the clone folder for the project
clone_folder: C:\projects\Vaporshell

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt
  Coveralls:
    secure: HbPIxwnQamh7cn5+oI68cfeDE0KSkfvwtlUckMyeKAYSRqDg4Iqg1zVQMIUuodLv

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1