environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt
  Coveralls:
    secure: r4c1f5ysoobhV4DGF9zc18yl+buyh7LoV7kRr7aUFvrcjd7VFmj71EPN0Egs9gOQ
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PowerShellEdition: "Core"
    - APPVEYOR_BUILD_WORKER_IMAGE: WMF 4
      PowerShellEdition: "4"
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: "5.1 / Core"
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

matrix:
  fast_finish: true

skip_commits:
  message: /updated readme.*|update readme.*s|\[skip ci\]|\[ci skip\]/

only_commits:
  message: /!deploy|!build|!ci|\[ci\]/

build: false

init:
  - ps: Write-Host $env:PYTHON $env:PYTHON_VERSION $env:PYTHON_ARCH

install:
  - sh: | 
      sudo -H apt-get -y install python-pip python-dev build-essential
      sudo -H pip install --upgrade pip
      sudo -H pip install --upgrade virtualenv
      sudo -H pip install --upgrade setuptools
      sudo -H pip install cfn_flip
  - cmd: "%PYTHON%/Scripts/pip.exe install cfn_flip"
test_script:
  - pwsh: >-
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE -notlike '*2015*') {
        $string = "Running PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'";
        Write-Host -ForegroundColor Magenta $string;
        . .\ci\init.ps1;
      } else {
        $string = "Skipping PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'";
        Write-Warning $string;
      }
  - ps: >-
      $string = "Running PowerShell $($PSVersionTable.PSVersion.ToString()) tests on image '$env:APPVEYOR_BUILD_WORKER_IMAGE'";
      Write-Host -ForegroundColor Magenta $string;
      . .\ci\init.ps1;