clone_folder: C:\projects\Vaporshell

image: 
  #- Ubuntu
  - Visual Studio 2017

environment:
  NuGetApiKey:
    secure: Ocp1ATd6eZ0eY9+LfZ9Stp9/J1B5eFdBPMdaTRWVa4xh6/NV45ZBYtU5+eemrTWt
  Coveralls:
    secure: r4c1f5ysoobhV4DGF9zc18yl+buyh7LoV7kRr7aUFvrcjd7VFmj71EPN0Egs9gOQ
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

skip_commits:
  message: /updated readme.*|update readme.*s|\[skip ci\]|\[ci skip\]/

only_commits:
  message: /!deploy|!build|!ci|\[ci\]/

build: false

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install cfn_flip"

test_script:
  - pwsh: . .\ci\init.ps1
  - ps: if ($isWindows) {. .\ci\init.ps1}