resources:
  repositories:
    - repository: templates
      type: github
      name: SCRT-HQ/AzurePipelineTemplates
      endpoint: Github

variables:
- group: deployment-vars

trigger:
  branches:
    include:
    - refs/heads/*

schedules:
  - cron: "0 16 * * 2"
    displayName: Weekly build on Tuesdays
    always: true
    branches:
      include:
        - master

stages:
- template: BuildTestDeployModule/azure-pipelines.yml@templates
