resources:
  repositories:
    - repository: templates
      type: github
      name: SCRT-HQ/AzurePipelineTemplates
      endpoint: Github

variables:
- group: deployment-vars

trigger:
  branches:
    include:
    - refs/heads/*

schedules:
  - cron: "0 19 * * 3"
    displayName: Weekly build on Wednesdays
    always: true
    branches:
      include:
        - master
        - beta

parameters:
  - name: BuildReleasePoolName
    default: 'windows-latest'
    type: string
    values:
      - windows-latest
      - ubuntu-latest
      - macOS-latest
  - name: IncludeDocker
    type: boolean
    default: true
  - name: TestBeta
    default: 'No'
    type: string
    values:
      - 'Yes'
      - 'No'

stages:
- template: BuildTestDeployModule/azure-pipelines.yml@templates
  parameters:
    BuildReleasePoolName: '{{ parameters.BuildReleasePoolName }}'
    TestBeta: ${{ parameters.TestBeta }}
    IncludeDocker: ${{ parameters.IncludeDocker }}
