resources:
  repositories:
    - repository: templates
      type: github
      name: SCRT-HQ/AzurePipelineTemplates
      endpoint: Github

variables:
- group: deployment-vars

trigger:
  branches:
    include:
    - refs/heads/*

schedules:
  - cron: "0 19 * * 3"
    displayName: Weekly build on Wednesdays
    always: true
    branches:
      include:
        - master
        - beta

stages:
- template: BuildTestDeployModule/azure-pipelines.yml@templates
  parameters:
    BuildReleasePoolName: 'Hosted VS2017'
    TestBeta: 'Yes'
