resources:
  repositories:
    - repository: templates
      type: github
      name: SCRT-HQ/AzurePipelineTemplates
      endpoint: Github

variables:
  - name: ModuleName
    value: VaporShell
  - group: deployment-vars

trigger:
  branches:
    include:
    - refs/heads/*
  paths:
    exclude:
      - '.devcontainer/*'
      - '.vscode/*'
      - '.github/*'
      - 'Deprecated/*'
      - '*.md'
      - 'LICENSE'
      - '*.code-workspace'
      - '.git*'
      - ClassPad.ps1
      - Install-VaporShell.ps1
      - _config.yml

schedules:
  - cron: "0 19 * * 3"
    displayName: Weekly BETA build on Wednesdays
    always: true
    branches:
      include:
        - beta
  - cron: "0 20 * * 3"
    displayName: Weekly PRD build on Wednesdays
    always: true
    branches:
      include:
        - main

parameters:
  - name: BuildReleasePoolName
    default: 'windows-latest'
    type: string
    values:
      - windows-latest
      - ubuntu-latest
      - macOS-latest
  - name: IncludeDocker
    type: boolean
    default: true

stages:
  - template: BuildTestDeployModule/azure-pipelines.yml@templates
    parameters:
      ModuleName: VaporShell
      BuildReleasePoolName: '${{ parameters.BuildReleasePoolName }}'
      TestBeta: 'Yes'
      IncludeDocker: ${{ parameters.IncludeDocker }}
