function Add-VSDataBrewJobS3TableOutputOptions {
    <#
    .SYNOPSIS
        Adds an AWS::DataBrew::Job.S3TableOutputOptions resource property to the template. Represents options that specify how and where DataBrew writes the Amazon S3 output generated by recipe jobs.

    .DESCRIPTION
        Adds an AWS::DataBrew::Job.S3TableOutputOptions resource property to the template.
Represents options that specify how and where DataBrew writes the Amazon S3 output generated by recipe jobs.

    .LINK
        http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-s3tableoutputoptions.html

    .PARAMETER Location
        Represents an Amazon S3 location bucket name and object key where DataBrew can write output from a job.

        Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-job-s3tableoutputoptions.html#cfn-databrew-job-s3tableoutputoptions-location
        UpdateType: Mutable
        Type: S3Location

    .FUNCTIONALITY
        Vaporshell
    #>
    [OutputType('Vaporshell.Resource.DataBrew.Job.S3TableOutputOptions')]
    [cmdletbinding()]
    Param
    (
        [parameter(Mandatory = $true)]
        $Location
    )
    Begin {
        $obj = [PSCustomObject]@{}
        $commonParams = @('Verbose','Debug','ErrorAction','WarningAction','InformationAction','ErrorVariable','WarningVariable','InformationVariable','OutVariable','OutBuffer','PipelineVariable')
    }
    Process {
        foreach ($key in $PSBoundParameters.Keys | Where-Object {$commonParams -notcontains $_}) {
            switch ($key) {
                Default {
                    $obj | Add-Member -MemberType NoteProperty -Name $key -Value $PSBoundParameters.$key
                }
            }
        }
    }
    End {
        $obj | Add-ObjectDetail -TypeName 'Vaporshell.Resource.DataBrew.Job.S3TableOutputOptions'
        Write-Verbose "Resulting JSON from $($MyInvocation.MyCommand): `n`n$($obj | ConvertTo-Json -Depth 5)`n"
    }
}
