name: Build and Deploy Docs
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build 🔧
        run: |
            . ./docs/ci/glossarydataCSVGenerator.ps1
            . ./docs/ci/glossaryUpdater.ps1
        shell: pwsh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          COMMIT_MESSAGE: '[skip ci] Updating docs from GitHub Actions'
