name: Build and Deploy Docs
permissions:
  contents: write
on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install PowerShell Modules 📦
        run: |
            Install-Module -Name platyPS -Force -Scope CurrentUser
        shell: pwsh
        
      - name: Build 🔧
        run: |
            . ./docs/ci/glossarydataCSVGenerator.ps1
            . ./docs/ci/glossaryUpdater.ps1
        shell: pwsh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ECP_TOKEN }}
          branch: gh-pages
          folder: docs
          commit-message: '[skip ci] Updating docs from GitHub Actions'
